chore: bump to `trader@v0.10.2`
valory-xyz/trader-quickstart pull request #157
Opened 2023-12-12 19:31 UTC by 0xArdi

This PR bumps to `trader@v0.10.2`.

2023-12-12 20:28 UTC, dagacha requested changes

2023-12-12 20:28 UTC, dagacha commented on run_service.sh
> +        if [ "$USE_STAKING" = true ]; thenhttps://github.com/valory-xyz/trader
This is odd @0xArdi please re-check

2023-12-13 09:19 UTC, 0xArdi commented on run_service.sh
> +        if [ "$USE_STAKING" = true ]; thenhttps://github.com/valory-xyz/trader
its a typo

2023-12-13 12:47 UTC, jmoreira-valory approved these changes

2023-12-14 16:28 UTC, dagacha approved these changes

2023-12-14 16:28 UTC, merged