Release `v0.12.1`
valory-xyz/trader-quickstart pull request #212
Opened 2024-01-30 16:24 UTC by Adamantios

2024-01-30 17:57 UTC, 0xArdi approved these changes

2024-01-31 09:41 UTC, jmoreira-valory requested changes
Waiting trader repo update.

2024-01-31 14:10 UTC, dagacha approved these changes

2024-01-31 14:11 UTC, jmoreira-valory approved these changes

2024-01-31 14:11 UTC, merged