Release `v0.16.5`
valory-xyz/trader-quickstart pull request #321
Opened 2024-07-15 13:21 UTC by Adamantios

2024-07-15 14:06 UTC, jmoreira-valory approved these changes

2024-07-16 07:52 UTC, dagacha requested changes
Actually this release is introducing breaking changes that need to be dealt with before merging.

```
File "/root/agent/vendor/valory/skills/decision_maker_abci/behaviours/storage_manager.py", line 277, in _update_accuracy_store
    accuracy_store = self.policy.accuracy_store
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^

AttributeError: 'dict' object has no attribute 'accuracy_store'
```

2024-07-19 10:36 UTC, Adamantios commented
> Actually this release is introducing breaking changes that need to be dealt with before merging.
> 
> ` File "/root/agent/vendor/valory/skills/decision_maker_abci/behaviours/storage_manager.py", line 277, in _update_accuracy_store accuracy_store = self.policy.accuracy_store ^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> AttributeError: 'dict' object has no attribute 'accuracy_store' `

This was addressed in https://github.com/valory-xyz/trader/pull/298.

2024-07-19 16:41 UTC, dagacha approved these changes

2024-07-19 17:09 UTC, merged