Script security - password protection
valory-xyz/trader-quickstart pull request #55
Opened 2023-10-18 20:13 UTC by jmoreira-valory

Feature to protect keys generated by the script.

2023-10-19 11:34 UTC, Adamantios commented on run_service.sh
> +    echo ""
These echo should be in the method no?

2023-10-19 11:46 UTC, jmoreira-valory commented on run_service.sh
> +    echo ""
fixed

2023-10-19 12:30 UTC, Adamantios approved these changes

2023-10-19 13:47 UTC, jmoreira-valory commented on run_service.sh
> +poetry run autonomy deploy run --build-dir $directory --detach || true
true is needed to proceed to clear the password stored by the framework, even if this command fails.

2023-11-20 10:44 UTC, jmoreira-valory commented
Bug https://github.com/valory-xyz/open-autonomy/issues/2088 has been fixed on https://github.com/valory-xyz/open-autonomy/pull/2108
Bug https://github.com/valory-xyz/open-autonomy/issues/2089 has been fixed on https://github.com/valory-xyz/open-autonomy/pull/2108

2023-11-20 16:01 UTC, jmoreira-valory commented on run_service.sh
> +poetry run autonomy deploy run --build-dir $directory --detach || true
Not needed anymore.

2023-11-20 16:12 UTC, Adamantios approved these changes

2023-11-21 15:47 UTC, Adamantios requested changes
Tested this and the password is not enforced. I do not agree with releasing this as is.

2023-11-21 15:50 UTC, jmoreira-valory commented
> Tested this and the password is not enforced. I do not agree with releasing this as is.

Please clarify what enforcements and where.

2023-11-21 16:02 UTC, Adamantios approved these changes
Tested this again. The script just fails later and not immediately.

2023-11-21 16:42 UTC, jmoreira-valory commented
> Tested this again. The script just fails later and not immediately.

Where? Please specify.

2023-11-21 17:01 UTC, merged